allowBuilds:
  '@heroui/shared-utils': true
  electron: true
  electron-winstaller: true
  '@loongdotjs/electron-winstaller': true
  esbuild: true
  meta-json-schema: true
overrides:
  typescript-eslint: ^8.59.2
  electron: 42.3.0
  electron-builder: npm:@loongdotjs/electron-builder@26.15.6
  vite: ^7.0.0
  '@vitejs/plugin-legacy': ^7.0.0
  '@vitejs/plugin-react': ^5.0.0
  rolldown: npm:@rolldown/binding-wasm32-wasi
  lightningcss: npm:lightningcss-wasm
  '@tailwindcss/oxide': npm:@tailwindcss/oxide-wasm32-wasi
patchedDependencies:
  monaco-worker-manager@2.0.1: patches/monaco-worker-manager@2.0.1.patch
publicHoistPattern:
  - '*@heroui/*'
shamefullyHoist: true
virtualStoreDirMaxLength: 80
